---
title: "PCA_AA"
author: "Eric Witte"
date: "2024-10-02"
output: html_document
---

#### Adapted from "Principal Component Analysis applied directly to Sequence Matrix" 
####  ~Tomokazu Konishi

##### R scripts for calculations

#load packages

library(rgl)
library(ggplot2)
library(tidyverse)
library(dplyr)

#set working directory

setwd("/Users/ericwitte/Documents/GitHub/Origins_of_Fish_Venoms")

### read & check the aligned sequence data:

ven_dat<- read.csv(file = "data/8425_213_aa_rmstop5.csv", sep = ",")

head(ven_dat)

ven_dat<- as.matrix(ven_dat)
dim(ven_dat)

##create variables for seqs

n_sample <- dim(ven_dat)[1]

n_seq <- nchar(ven_dat[1,2])

#translation of the sequence to boolean vectors

bool <- array(0, dim=c(n_sample, 21*n_seq))


colnames(bool) <- c(paste("A_", 1:n_seq, sep=""),paste("C_", 1:n_seq, sep=""),paste("D_", 1:n_seq, sep=""),paste("E_", 1:n_seq, sep=""),paste("F_", 1:n_seq, sep=""),paste("G_", 1:n_seq, sep=""),paste("H_", 1:n_seq, sep=""),paste("I_", 1:n_seq, sep=""),paste("K_", 1:n_seq, sep=""),paste("L_", 1:n_seq, sep=""),paste("M_", 1:n_seq, sep=""),paste("N_", 1:n_seq, sep=""),paste("P_", 1:n_seq, sep=""),paste("Q_", 1:n_seq, sep=""),paste("R_", 1:n_seq, sep=""),paste("S_", 1:n_seq, sep=""),paste("T_", 1:n_seq, sep=""),paste("V_", 1:n_seq, sep=""),paste("W_", 1:n_seq, sep=""),paste("Y_", 1:n_seq, sep=""),paste("-_", 1:n_seq, sep=""))

rownames(bool) <- ven_dat[,1]


  for (s in 1:n_sample){
     se <- ven_dat[s, 2]
     se <- tolower(se)

	for (le in  1:n_seq){

	 base <- substr(se, le,le)
 
	if(base =="a") {
	bool[s, le] <-1
		} else {

	if(base =="c") {
	bool[s, le+n_seq] <-1
		} else {

	if(base =="d") {
	bool[s, le+n_seq*2] <-1
		} else {

	if(base =="e") {
	bool[s, le+n_seq*3] <-1
		} else {

	if(base =="f") {
	bool[s, le+n_seq*4] <-1
		} else {

	if(base =="g") {
	bool[s, le+n_seq*5] <-1
		} else {

	if(base =="h") {
	bool[s, le+n_seq*6] <-1
		} else {

	if(base =="i") {
	bool[s, le+n_seq*7] <-1
		} else {

	if(base =="k") {
	bool[s, le+n_seq*8] <-1
		} else {

	if(base =="l") {
	bool[s, le+n_seq*9] <-1
		} else {

	if(base =="m") {
	bool[s, le+n_seq*10] <-1
		} else {

	if(base =="n") {
	bool[s, le+n_seq*11] <-1
		} else {

	if(base =="p") {
	bool[s, le+n_seq*12] <-1
		} else {

	if(base =="q") {
	bool[s, le+n_seq*13] <-1
		} else {

	if(base =="r") {
	bool[s, le+n_seq*14] <-1
		} else {

	if(base =="s") {
	bool[s, le+n_seq*15] <-1
		} else {

	if(base =="t") {
	bool[s, le+n_seq*16] <-1
		} else {

	if(base =="v") {
	bool[s, le+n_seq*17] <-1
		} else {

	if(base =="w") {
	bool[s, le+n_seq*18] <-1
		} else {

	if(base =="y") {
	bool[s, le+n_seq*19] <-1
		} else {

	if(base =="-") {
	bool[s, le+n_seq*20] <-1

	}}}}}}}}}}}}}}}}}}}}}
	}}
	
#PCA
## centering : the center can be replaced to certain group
	center<- apply(bool, 2, mean)
	diffs<-sweep(bool, 2, center)
        diffs<-diffs/2^0.5  # dounble counting
# checking distribution of the distances
    		dist<- (apply(diffs^2, 1, sum)/n_seq)^0.5
        	qqnorm(dist)
		hist(dist)
		  
### PCA core
	
	res_svd <- svd(diffs)  #
	str(res_svd)
			Left <- res_svd$u		# the left singular vectors
			Right <- res_svd$v		# the right singular vectors
			sqL <- diag(res_svd$d)		# diagonal matrix of the singular values

### calculating of pc's 
	sPC_res  	<-	 Right %*% sqL / (n_sample^0.5)
	sPC_sample	 <-	 Left %*% sqL/ (n_seq^0.5)

	rownames(sPC_res)<- colnames(bool) 
 	rownames(sPC_sample)<- rownames(bool) 

write.table(sPC_sample, file="sPC_sample_full.txt", sep="\t")
	write.table(sPC_res, file="sPC_res_full.txt", sep="\t")

(sum(diffs^2)/n_seq)^0.5

#### output to png images
# sample
	png(width=2100, height=2300, pointsize = 80, file="figs/8425_sPC_full_aa.png")
	  par(lwd=4, mex=0.6, mai=c(4,4,3,0.2))
  	  plot( sPC_sample [,1], sPC_sample[,2], col="gray50" ,  pch=1, main="sample", xlab="", ylab="" , axes=T)
	dev.off()

# sites
	png(width=2100, height=2300, pointsize = 80, file="figs/8425_sPC_res_full_aa.png")
	  par(lwd=4, mex=0.6, mai=c(4,4,3,0.2))
  	  plot( sPC_res [,1], sPC_res[,2], col="gray50" ,  pch=1, main="residure", xlab="", ylab="" , axes=T)
	dev.off()

 # contribution
	png(width=2100, height=2300, pointsize = 80, file="figs/8425_full_contributions.png")
	  par(lwd=4, mex=0.6, mai=c(4,4,3,0.2))
	  plot(1:20, (res_svd$d/sum(res_svd$d)*100)[1:20], pch=1, type="b",  lty=3, ylab="(%)", xlab="PC", main="Contribution", col="gray50")
	dev.off()
	
	contrib <- (res_svd$d/sum(res_svd$d)*100)[1:20]
	contrib #prints contribution of each PC


# 3D presentation

 plot3d( sPC_sample [,1], sPC_sample[,2], sPC_sample[,3], col="black", pch=NA, main="Stx", xlab="sPC1", ylab="sPC2", zlab="sPC3", type="p")
 #  text3d( sPC_sample [,1], sPC_sample[,2], sPC_sample[,3], texts=sites[,1], cex=.5, col="gray50", font=1)
 writeWebGL(width=700)


plot(sPC_sample[,1],sPC_sample[,2], col = "black", xlab="sPC1", ylab= "sPC2")


df_sPC_sample <- as.data.frame(sPC_sample)

df_sPC_sample$subunit <- ven_dat[,3]

df_sPC_sample$clade <- ven_dat[,4]

View(df_sPC_sample)

g <- ggplot(df_sPC_sample, aes(x=V1, y=V2)) + geom_point(aes(col = subunit, shape = clade, size = subunit)) + xlab("PC 1 (3.22%)") + ylab("PC 2 (2.65%)") + scale_color_manual(values = c("A" = "steelblue2", "B" = "orchid", "Unknown" = "black")) + scale_shape_manual(values = c("0" = 3, "1" =4, "2" = 2, "3" = 5, "4"=1)) + scale_size_manual( values = c("Unknown" = 2, "A" = 3, "B" = 3))

<- g <- ggplot(df_sPC_sample, aes(x=V1, y=V2)) + geom_point(aes(col = subunit, shape = subunit, size = subunit)) + xlab("PC 1 (3.22%)") + ylab("PC 2 (2.65%)") + scale_color_manual(values = c("Unknown" = "black", "A" = "steelblue2", "B" = "orchid"))  + theme(aspect.ratio = 1) + scale_shape_manual(values = c("0" = 3, "1" =4, "2" = 2, "3" = 5, "4"=1)) + scale_size_manual( values = c("Unknown" = 2, "A" = 3, "B" = 3)) 

ggsave(plot = g, filename = "figs/8425_pc1pc2.png", )


#outlier sites

ven_dat_df<- as.data.frame(ven_dat)

comp_bool <- data.frame(bool) %>% 
  add_column(ven_dat_df$Subunit) %>% 
  add_column(ven_dat_df$Clade)
  
last_col <- ncol(comp_bool)

colnames(comp_bool)[(last_col-1)] <- "subunit"

colnames(comp_bool)[last_col] <- "clade"

View(comp_bool)

#Subunit

temp_sub <- data.frame(matrix(0, nrow = nrow(comp_bool), ncol = 2))

temp_sub[,2] <- comp_bool$subunit

colnames(temp_sub) <- c("b", "subunit")

rownames(temp_sub) <- rownames(comp_bool)

View(temp_sub)

tally_sub <- data.frame(matrix(0, ncol = 6, nrow = (ncol(comp_bool)-2)))

rownames(tally_sub) <- colnames(comp_bool[1:(last_col-2)])

colnames(tally_sub) <- c("A", "B", "U", "A-B", "A-U", "B-U")


for(a in 1:(last_col-2)){
  temp_sub$b <- comp_bool[,a]
  
 q<- temp_sub %>% 
    group_by(subunit) %>% 
    summarize(Mean = mean(b, na.rm = TRUE)) %>% 
    ungroup()
    
    tally_sub[a,1] <- q[1,2]
    tally_sub[a,2] <- q[2,2]
    tally_sub[a,3] <- q[3,2]
    tally_sub[a,4] <- tally_sub[a,1]-tally_sub[a,2] # could change to abs val
    tally_sub[a,5] <- tally_sub[a,1]-tally_sub[a,3]
    tally_sub[a,6] <- tally_sub[a,2]-tally_sub[a,3]
    
    rm(q)
    print(a)
    }
  
  View(tally_)
  
#clade

temp_clade <- data.frame(matrix(0, nrow = nrow(comp_bool), ncol = 2))

temp_clade[,2] <- as.character(comp_bool$clade)

colnames(temp_clade) <- c("b", "clade")

rownames(temp_clade) <- rownames(comp_bool)

View(temp_clade)

tally_clade <- data.frame(matrix(0, ncol = 17, nrow = (ncol(comp_bool)-2)))

rownames(tally_clade) <- colnames(comp_bool[1:(last_col-2)])

colnames(tally_clade) <- c("0", "1", "2", "3", "4", "0-1", "0-2", "0-3", "1-2", "1-3", "2-3", "1-4", "2-4", "3-4", "123-0", "123-4", "12-4")


for(a in 1:(last_col-2)){
  temp_clade$b <- comp_bool[,a]
  
 q<- temp_clade %>% 
    group_by(clade) %>% 
    summarize(Mean = mean(b, na.rm = TRUE)) %>% 
    ungroup()
    
    tally_clade[a,1] <- q[1,2]
    tally_clade[a,2] <- q[2,2]
    tally_clade[a,3] <- q[3,2]
    tally_clade[a,4] <- q[4,2]
    tally_clade[a,5] <- q[5,2]
    tally_clade[a,6] <- tally_clade[a,1]-tally_clade[a,2] # could change to abs val
    tally_clade[a,7] <- tally_clade[a,1]-tally_clade[a,3]
    tally_clade[a,8] <- tally_clade[a,1]-tally_clade[a,4]
    tally_clade[a,9] <- tally_clade[a,2]-tally_clade[a,3]
    tally_clade[a,10] <-tally_clade[a,2]-tally_clade[a,4]
    tally_clade[a,11] <- tally_clade[a,3]-tally_clade[a,4]
    tally_clade[a,12] <- tally_clade[a,2]-tally_clade[a,5]
    tally_clade[a,13] <- tally_clade[a,3]-tally_clade[a,5]
    tally_clade[a,14] <- tally_clade[a,4]-tally_clade[a,5]
    tally_clade[a,15] <- tally_clade[a,2] + tally_clade[a,3] + tally_clade[a,4] - tally_clade[a,1] 
    tally_clade[a,16] <- tally_clade[a,2] + tally_clade[a,3] + tally_clade[a,4] - tally_clade[a,5]
    tally_clade[a,17] <- tally_clade[a,2] + tally_clade[a,3] - tally_clade[a,5]
    
    rm(q)
    print(a)
    }
  
  View(tally_clade)
  


#outlier sites
library(tidyverse)
library(dplyr)

ven_dat_df<- as.data.frame(ven_dat)

comp_bool <- data.frame(bool) %>% 
  add_column(ven_dat_df$subunit) %>% 
  add_column(ven_dat_df$ven_clade)
  
last_col <- ncol(comp_bool)

colnames(comp_bool)[(last_col-1)] <- "subunit"

colnames(comp_bool)[last_col] <- "clade"

View(comp_bool)

#Subunit

temp_sub <- data.frame(matrix(0, nrow = nrow(comp_bool), ncol = 2))

temp_sub[,2] <- comp_bool$subunit

colnames(temp_sub) <- c("b", "subunit")

rownames(temp_sub) <- rownames(comp_bool)

View(temp_sub)

tally_sub <- data.frame(matrix(0, ncol = 6, nrow = (ncol(comp_bool)-2)))

rownames(tally_sub) <- colnames(comp_bool[1:(last_col-2)])

colnames(tally_sub) <- c("A", "B", "U", "A-B", "A-U", "B-U")


for(a in 1:(last_col-2)){
  temp_sub$b <- comp_bool[,a]
  
 q<- temp_sub %>% 
    group_by(subunit) %>% 
    summarize(Mean = mean(b, na.rm = TRUE)) %>% 
    ungroup()
    
    tally_sub[a,1] <- q[1,2]
    tally_sub[a,2] <- q[2,2]
    tally_sub[a,3] <- q[3,2]
    tally_sub[a,4] <- tally_sub[a,1]-tally_sub[a,2] # could change to abs val
    tally_sub[a,5] <- tally_sub[a,1]-tally_sub[a,3]
    tally_sub[a,6] <- tally_sub[a,2]-tally_sub[a,3]
    
    rm(q)
    print(a)
    }
  
  View(tally_sub)
  
#clade

temp_clade <- data.frame(matrix(0, nrow = nrow(comp_bool), ncol = 2))

temp_clade[,2] <- as.character(comp_bool$clade)

colnames(temp_clade) <- c("b", "clade")

rownames(temp_clade) <- rownames(comp_bool)

View(temp_clade)

tally_clade <- data.frame(matrix(0, ncol = 7, nrow = (ncol(comp_bool)-2)))

rownames(tally_clade) <- colnames(comp_bool[1:(last_col-2)])

colnames(tally_clade) <- c("0", "1", "2", "0-1", "0-2", "1-2", "0v1+2")


for(a in 1:(last_col-2)){
  temp_clade$b <- comp_bool[,a]
  
 q<- temp_clade %>% 
    group_by(clade) %>% 
    summarize(Mean = mean(b, na.rm = TRUE)) %>% 
    ungroup()
    
    tally_clade[a,1] <- q[1,2]
    tally_clade[a,2] <- q[2,2]
    tally_clade[a,3] <- q[3,2]
    tally_clade[a,4] <- tally_clade[a,1]-tally_clade[a,2] # could change to abs val
    tally_clade[a,5] <- tally_clade[a,1]-tally_clade[a,3]
    tally_clade[a,6] <- tally_clade[a,2]-tally_clade[a,3]
    tally_clade[a,7] <- (tally_clade[a,1] - ((tally_clade[a,2]+tally_clade[a,3])/2))
    
    rm(q)
    print(a)
    }
  
  View(tally_clade)

  
  


